### ISSUE TITLE
Cannot edit style names

### ISSUE THREAD

**Issue by Pixelshark40004** [eternalUnion/UltrakillStyleEditor#1]
I installed the mod with the proper dependencies, and yet I cannot change style names at all. Can’t even make them bold or change their color. The settings either reset, or i can’t even click on the name to edit it.

**Comment by eternalUnion** [comment]
Hi, I need a little bit more info to solve the issue:
* Are there any errors on the console log?
* Are you clicking the correct button? You should not click on the name but the pen icon just next to the style name
* Pressing ESC can cancel the field (it is a feature of the unity input system), to disable it go to PLUGIN CONFIG > Plugin Configurator > Cancel on ESC (disable)

**Comment by Pixelshark40004** [comment]
Restarted my game a few times, and reinstalled PluginConfigurator, suddenly works. Probably some broken file registry or something. Anyways, good mod

**Comment by Megarion** [comment]
I couldn't edit the style names, but after a reinstall, I found out that you can click to the right of the textbox and it will let you edit it
