### ISSUE TITLE
FRIED isn't working

### ISSUE THREAD

**Issue by TheTurd125** [eternalUnion/UltrakillStyleEditor#2]
![hmmm](https://github.com/eternalUnion/UltrakillStyleEditor/assets/79824410/e4c20775-a5d3-4cb5-b68a-84c3de35062d)

**Comment by eternalUnion** [comment]
Fixed by v1.0.1
https://github.com/eternalUnion/UltrakillStyleEditor/releases/tag/v1.0.1
