### ISSUE TITLE
[ENHANCEMENT] Permit manual input of RGB Number Values + Maybe a field to input a hex code instead

### ISSUE THREAD

**Issue by UntotenTheo** [eternalUnion/UltrakillStyleEditor#4]
cant add labels lol anyways hi eu
am I seriously opening a suggestion 2 month after the last update? yea lol (i dont expect this to be added)

Anyways, I think this would make editing style bonuses far easier, and would make Multi-Colored edits significantly easier to do

**Comment by eternalUnion** [comment]
This is a plugin configurator feature so I will transfer it over there when I start working on it

**Comment by UntotenTheo** [comment]
thanks eu
closing issue
