### ISSUE TITLE
[BUG] Conductor

### ISSUE THREAD

**Issue by UntotenTheo** [eternalUnion/UltrakillStyleEditor#5]
# Description
Conductor is really weird, you can edit it from the Hurt Style Bonuses menu, but executing it in-game displays the default Conductor bonus. Said bonus appears in the Unknown Styles tab, changing that doesn't fix the issue and the style bonus will still appear as default

# Reproduction
* Step 1: Change Conductor Style Bonus
* Step 2: Trigger Conductor
* Step 3: It's not displaying as intended

# Plugins Used
* Ultrakill Style Editor: 1.0.2
* Plugin Configurator: 1.8.4

**Comment by eternalUnion** [comment]
I have found the issue, an update will be released when styles from violence are added, alongside some other qol changes.

**Comment by UntotenTheo** [comment]
thanks eu

**Comment by eternalUnion** [comment]
Fixed as of [v1.0.3](https://github.com/eternalUnion/UltrakillStyleEditor/releases/tag/v1.0.3)
